import type { Category, CategoryRule } from "./types";

/** Initial MVP categories agreed in the product brief. */
export const DEFAULT_CATEGORIES: Category[] = [
  { id: "cat_logement", name: "Logement", behavior: "spending" },
  { id: "cat_courses", name: "Courses", behavior: "spending" },
  { id: "cat_restos", name: "Restos", behavior: "spending" },
  { id: "cat_soirees", name: "Soirees", behavior: "spending" },
  { id: "cat_voyages", name: "Voyages", behavior: "spending" },
  { id: "cat_habits", name: "Habits", behavior: "spending" },
  { id: "cat_abonnements", name: "Abonnements", behavior: "spending" },
  { id: "cat_dons", name: "Dons", behavior: "spending" },
  { id: "cat_cagnottes", name: "Cagnottes", behavior: "spending" },
  { id: "cat_travaux", name: "Travaux", behavior: "spending" },
  { id: "cat_bricolage", name: "Bricolage", behavior: "spending" },
  { id: "cat_sante", name: "Sante", behavior: "spending" },
  { id: "cat_sport", name: "Sport", behavior: "spending" },
  { id: "cat_loisirs", name: "Loisirs", behavior: "spending" },
  { id: "cat_revenus", name: "Revenus", behavior: "income" },
  { id: "cat_transfert", name: "Virement interne", behavior: "transfer" },
  { id: "cat_autre", name: "Autre", behavior: "spending" },
];

/**
 * Starter rules. Ordered by `priority`; the first matching rule wins.
 * Users can edit, reorder, add, or remove rules — this is only a sensible seed.
 */
export const DEFAULT_CATEGORY_RULES: CategoryRule[] = [
  { id: "r_vir_interne", pattern: "virement interne", isRegex: false, priority: 1, targetCategoryId: "cat_transfert" },
  { id: "r_vir_fortuneo", pattern: "virement avec fortuneo", isRegex: false, priority: 1, targetCategoryId: "cat_transfert" },
  { id: "r_vir_vers_paul", pattern: "vers paul mondou", isRegex: false, priority: 1, targetCategoryId: "cat_transfert" },
  { id: "r_vir_achat_paul", pattern: "achat paul mondou", isRegex: false, priority: 1, targetCategoryId: "cat_transfert" },
  { id: "r_salaire", pattern: "salaire", isRegex: false, priority: 5, targetCategoryId: "cat_revenus" },
  { id: "r_loyer", pattern: "loyer", isRegex: false, priority: 10, targetCategoryId: "cat_logement" },
  { id: "r_edf", pattern: "edf", isRegex: false, priority: 10, targetCategoryId: "cat_logement" },
  { id: "r_engie", pattern: "engie", isRegex: false, priority: 10, targetCategoryId: "cat_logement" },
  { id: "r_eau", pattern: "facture eau", isRegex: false, priority: 10, targetCategoryId: "cat_logement" },
  { id: "r_assurance_habitation", pattern: "assurance habitation", isRegex: false, priority: 10, targetCategoryId: "cat_logement" },
  { id: "r_carrefour", pattern: "carrefour", isRegex: false, priority: 20, targetCategoryId: "cat_courses" },
  { id: "r_leclerc", pattern: "leclerc", isRegex: false, priority: 20, targetCategoryId: "cat_courses" },
  { id: "r_lidl", pattern: "lidl", isRegex: false, priority: 20, targetCategoryId: "cat_courses" },
  { id: "r_monoprix", pattern: "monoprix", isRegex: false, priority: 20, targetCategoryId: "cat_courses" },
  { id: "r_franprix", pattern: "franprix", isRegex: false, priority: 20, targetCategoryId: "cat_courses" },
  { id: "r_auchan", pattern: "auchan", isRegex: false, priority: 20, targetCategoryId: "cat_courses" },
  { id: "r_intermarche", pattern: "intermarche", isRegex: false, priority: 20, targetCategoryId: "cat_courses" },
  { id: "r_picard", pattern: "picard", isRegex: false, priority: 20, targetCategoryId: "cat_courses" },
  { id: "r_la_louve", pattern: "la louve", isRegex: false, priority: 20, targetCategoryId: "cat_courses" },
  { id: "r_coop_louve", pattern: "cooplalouve", isRegex: false, priority: 20, targetCategoryId: "cat_courses" },
  { id: "r_restaurant", pattern: "restaurant", isRegex: false, priority: 25, targetCategoryId: "cat_restos" },
  { id: "r_resto", pattern: "resto", isRegex: false, priority: 25, targetCategoryId: "cat_restos" },
  { id: "r_brasserie", pattern: "brasserie", isRegex: false, priority: 25, targetCategoryId: "cat_restos" },
  { id: "r_cafe", pattern: "cafe", isRegex: false, priority: 25, targetCategoryId: "cat_restos" },
  { id: "r_swile", pattern: "swile", isRegex: false, priority: 25, targetCategoryId: "cat_restos" },
  { id: "r_newrest", pattern: "newrest", isRegex: false, priority: 25, targetCategoryId: "cat_restos" },
  { id: "r_ete_parisien", pattern: "ete parisien", isRegex: false, priority: 25, targetCategoryId: "cat_restos" },
  { id: "r_chez_papa", pattern: "chez papa", isRegex: false, priority: 25, targetCategoryId: "cat_restos" },
  { id: "r_ay_simo", pattern: "ay simo", isRegex: false, priority: 25, targetCategoryId: "cat_restos" },
  { id: "r_the_nines", pattern: "the nines", isRegex: false, priority: 25, targetCategoryId: "cat_restos" },
  { id: "r_pere_fish", pattern: "pere et fish", isRegex: false, priority: 25, targetCategoryId: "cat_restos" },
  { id: "r_yellow_kitchens", pattern: "yellow kitchens", isRegex: false, priority: 25, targetCategoryId: "cat_restos" },
  { id: "r_potager", pattern: "potager", isRegex: false, priority: 25, targetCategoryId: "cat_restos" },
  { id: "r_inter_co", pattern: "l'inter-co", isRegex: false, priority: 25, targetCategoryId: "cat_restos" },
  { id: "r_bloom", pattern: "bloom", isRegex: false, priority: 25, targetCategoryId: "cat_restos" },
  { id: "r_uber_eats", pattern: "uber\\s?eats", isRegex: true, priority: 25, targetCategoryId: "cat_restos" },
  { id: "r_deliveroo", pattern: "deliveroo", isRegex: false, priority: 25, targetCategoryId: "cat_restos" },
  { id: "r_mcdonalds", pattern: "mc ?donald", isRegex: true, priority: 25, targetCategoryId: "cat_restos" },
  { id: "r_burger_king", pattern: "burger king", isRegex: false, priority: 25, targetCategoryId: "cat_restos" },
  { id: "r_sncf", pattern: "sncf", isRegex: false, priority: 30, targetCategoryId: "cat_voyages" },
  { id: "r_ouigo", pattern: "ouigo", isRegex: false, priority: 30, targetCategoryId: "cat_voyages" },
  { id: "r_trainline", pattern: "trainline", isRegex: false, priority: 30, targetCategoryId: "cat_voyages" },
  { id: "r_booking", pattern: "booking", isRegex: false, priority: 30, targetCategoryId: "cat_voyages" },
  { id: "r_airbnb", pattern: "airbnb", isRegex: false, priority: 30, targetCategoryId: "cat_voyages" },
  { id: "r_hotel", pattern: "hotel", isRegex: false, priority: 30, targetCategoryId: "cat_voyages" },
  { id: "r_air_france", pattern: "air france", isRegex: false, priority: 30, targetCategoryId: "cat_voyages" },
  { id: "r_transavia", pattern: "transavia", isRegex: false, priority: 30, targetCategoryId: "cat_voyages" },
  { id: "r_easyjet", pattern: "easyjet", isRegex: false, priority: 30, targetCategoryId: "cat_voyages" },
  { id: "r_ryanair", pattern: "ryanair", isRegex: false, priority: 30, targetCategoryId: "cat_voyages" },
  { id: "r_getaround", pattern: "getaround", isRegex: false, priority: 30, targetCategoryId: "cat_voyages" },
  { id: "r_sejour_montagne", pattern: "sejour montagne", isRegex: false, priority: 30, targetCategoryId: "cat_voyages" },
  { id: "r_navigo", pattern: "navigo", isRegex: false, priority: 30, targetCategoryId: "cat_voyages" },
  { id: "r_zara", pattern: "zara", isRegex: false, priority: 35, targetCategoryId: "cat_habits" },
  { id: "r_hm", pattern: "\\bh\\s*&?\\s*m\\b", isRegex: true, priority: 35, targetCategoryId: "cat_habits" },
  { id: "r_uniqlo", pattern: "uniqlo", isRegex: false, priority: 35, targetCategoryId: "cat_habits" },
  { id: "r_kiabi", pattern: "kiabi", isRegex: false, priority: 35, targetCategoryId: "cat_habits" },
  { id: "r_vinted", pattern: "vinted", isRegex: false, priority: 35, targetCategoryId: "cat_habits" },
  { id: "r_zalando", pattern: "zalando", isRegex: false, priority: 35, targetCategoryId: "cat_habits" },
  { id: "r_asos", pattern: "asos", isRegex: false, priority: 35, targetCategoryId: "cat_habits" },
  { id: "r_jules", pattern: "jules", isRegex: false, priority: 35, targetCategoryId: "cat_habits" },
  { id: "r_mango", pattern: "mango", isRegex: false, priority: 35, targetCategoryId: "cat_habits" },
  { id: "r_sephora", pattern: "sephora", isRegex: false, priority: 35, targetCategoryId: "cat_habits" },
  { id: "r_leroymerlin", pattern: "leroy merlin", isRegex: false, priority: 40, targetCategoryId: "cat_travaux" },
  { id: "r_castorama_travaux", pattern: "castorama", isRegex: false, priority: 40, targetCategoryId: "cat_travaux" },
  { id: "r_bricodepot_travaux", pattern: "brico depot", isRegex: false, priority: 40, targetCategoryId: "cat_travaux" },
  { id: "r_bricorama_travaux", pattern: "bricorama", isRegex: false, priority: 40, targetCategoryId: "cat_travaux" },
  { id: "r_lapeyre_travaux", pattern: "lapeyre", isRegex: false, priority: 40, targetCategoryId: "cat_travaux" },
  { id: "r_mano_mano_travaux", pattern: "manomano", isRegex: false, priority: 40, targetCategoryId: "cat_travaux" },
  { id: "r_adeo_travaux", pattern: "adeo", isRegex: false, priority: 40, targetCategoryId: "cat_travaux" },
  { id: "r_leroy_merli_travaux", pattern: "leroy merli", isRegex: false, priority: 40, targetCategoryId: "cat_travaux" },
  { id: "r_maison_pigot_travaux", pattern: "maison pigot", isRegex: false, priority: 40, targetCategoryId: "cat_travaux" },
  { id: "r_darty_travaux", pattern: "darty", isRegex: false, priority: 40, targetCategoryId: "cat_travaux" },
  { id: "r_ikea_travaux", pattern: "ikea", isRegex: false, priority: 40, targetCategoryId: "cat_travaux" },
  { id: "r_centrale_verre_travaux", pattern: "centrale du verre", isRegex: false, priority: 40, targetCategoryId: "cat_travaux" },
  { id: "r_vevor_travaux", pattern: "vevor", isRegex: false, priority: 40, targetCategoryId: "cat_travaux" },
  { id: "r_racetools_travaux", pattern: "racetools", isRegex: false, priority: 40, targetCategoryId: "cat_travaux" },
  { id: "r_cecotec_travaux", pattern: "cecot ec|cecotec", isRegex: true, priority: 40, targetCategoryId: "cat_travaux" },
  { id: "r_cdiscount_travaux", pattern: "cdiscount", isRegex: false, priority: 40, targetCategoryId: "cat_travaux" },
  { id: "r_camca_logement", pattern: "camca", isRegex: false, priority: 42, targetCategoryId: "cat_logement" },
  { id: "r_pret_logement", pattern: "remboursement de pret", isRegex: false, priority: 42, targetCategoryId: "cat_logement" },
  { id: "r_credit_logement", pattern: "frais de dossier de credit", isRegex: false, priority: 42, targetCategoryId: "cat_logement" },
  { id: "r_matmut_logement", pattern: "matmut", isRegex: false, priority: 42, targetCategoryId: "cat_logement" },
  { id: "r_pharma", pattern: "pharmacie", isRegex: false, priority: 45, targetCategoryId: "cat_sante" },
  { id: "r_doctolib", pattern: "doctolib", isRegex: false, priority: 45, targetCategoryId: "cat_sante" },
  { id: "r_medecin", pattern: "medecin", isRegex: false, priority: 45, targetCategoryId: "cat_sante" },
  { id: "r_decathlon", pattern: "decathlon", isRegex: false, priority: 50, targetCategoryId: "cat_sport" },
  { id: "r_basic_fit", pattern: "basic fit", isRegex: false, priority: 50, targetCategoryId: "cat_sport" },
  { id: "r_arkose", pattern: "arkose", isRegex: false, priority: 50, targetCategoryId: "cat_sport" },
  { id: "r_foulees", pattern: "foulees", isRegex: false, priority: 50, targetCategoryId: "cat_sport" },
  { id: "r_body_fit", pattern: "body fit", isRegex: false, priority: 50, targetCategoryId: "cat_sport" },
  { id: "r_speck_sports", pattern: "speck sports", isRegex: false, priority: 50, targetCategoryId: "cat_sport" },
  { id: "r_nutripure", pattern: "nutripure", isRegex: false, priority: 50, targetCategoryId: "cat_sport" },
  { id: "r_theatre", pattern: "theatre", isRegex: false, priority: 55, targetCategoryId: "cat_loisirs" },
  { id: "r_billetweb", pattern: "billetweb", isRegex: false, priority: 55, targetCategoryId: "cat_loisirs" },
  { id: "r_shotgun", pattern: "shotgun", isRegex: false, priority: 55, targetCategoryId: "cat_loisirs" },
  { id: "r_gibert", pattern: "gibert joseph", isRegex: false, priority: 55, targetCategoryId: "cat_loisirs" },
  { id: "r_lovely_planet", pattern: "lovely planet", isRegex: false, priority: 55, targetCategoryId: "cat_loisirs" },
  { id: "r_sudden_theatre", pattern: "sudden theatre", isRegex: false, priority: 55, targetCategoryId: "cat_loisirs" },
  { id: "r_ticketmaster", pattern: "ticketmaster", isRegex: false, priority: 55, targetCategoryId: "cat_loisirs" },
  { id: "r_tattoo", pattern: "tattoo", isRegex: false, priority: 55, targetCategoryId: "cat_loisirs" },
  { id: "r_netflix", pattern: "netflix", isRegex: false, priority: 60, targetCategoryId: "cat_abonnements" },
  { id: "r_spotify", pattern: "spotify", isRegex: false, priority: 60, targetCategoryId: "cat_abonnements" },
  { id: "r_deezer", pattern: "deezer", isRegex: false, priority: 60, targetCategoryId: "cat_abonnements" },
  { id: "r_disney", pattern: "disney", isRegex: false, priority: 60, targetCategoryId: "cat_abonnements" },
  { id: "r_canal", pattern: "canal", isRegex: false, priority: 60, targetCategoryId: "cat_abonnements" },
  { id: "r_amazon_prime", pattern: "amazon prime", isRegex: false, priority: 60, targetCategoryId: "cat_abonnements" },
  { id: "r_prime_video", pattern: "prime video", isRegex: false, priority: 60, targetCategoryId: "cat_abonnements" },
  { id: "r_apple", pattern: "apple.com/bill", isRegex: false, priority: 60, targetCategoryId: "cat_abonnements" },
  { id: "r_google", pattern: "google", isRegex: false, priority: 60, targetCategoryId: "cat_abonnements" },
  { id: "r_adobe", pattern: "adobe", isRegex: false, priority: 60, targetCategoryId: "cat_abonnements" },
  { id: "r_icloud", pattern: "icloud", isRegex: false, priority: 60, targetCategoryId: "cat_abonnements" },
  { id: "r_free_mobile", pattern: "free mobile", isRegex: false, priority: 60, targetCategoryId: "cat_abonnements" },
  { id: "r_free_telecom", pattern: "free telecom", isRegex: false, priority: 60, targetCategoryId: "cat_abonnements" },
  { id: "r_sfr", pattern: "sfr", isRegex: false, priority: 60, targetCategoryId: "cat_abonnements" },
  { id: "r_bouygues", pattern: "bouygues", isRegex: false, priority: 60, targetCategoryId: "cat_abonnements" },
  { id: "r_orange", pattern: "orange", isRegex: false, priority: 60, targetCategoryId: "cat_abonnements" },
  { id: "r_helloasso", pattern: "helloasso", isRegex: false, priority: 65, targetCategoryId: "cat_dons" },
  { id: "r_don", pattern: "\\bdon\\b", isRegex: true, priority: 65, targetCategoryId: "cat_dons" },
  { id: "r_refuge", pattern: "refuge", isRegex: false, priority: 65, targetCategoryId: "cat_dons" },
  { id: "r_pasteur", pattern: "pasteur", isRegex: false, priority: 65, targetCategoryId: "cat_dons" },
  { id: "r_croix_rouge", pattern: "croix rouge", isRegex: false, priority: 65, targetCategoryId: "cat_dons" },
  { id: "r_unicef", pattern: "unicef", isRegex: false, priority: 65, targetCategoryId: "cat_dons" },
  { id: "r_msf", pattern: "medecins sans frontieres", isRegex: false, priority: 65, targetCategoryId: "cat_dons" },
  { id: "r_leetchi", pattern: "leetchi", isRegex: false, priority: 70, targetCategoryId: "cat_cagnottes" },
  { id: "r_lydia_cagnotte", pattern: "cagnotte", isRegex: false, priority: 70, targetCategoryId: "cat_cagnottes" },
  { id: "r_lepotcommun", pattern: "le pot commun", isRegex: false, priority: 70, targetCategoryId: "cat_cagnottes" },
  { id: "r_papayoux", pattern: "papayoux", isRegex: false, priority: 70, targetCategoryId: "cat_cagnottes" },
  { id: "r_anniversaire", pattern: "anniversaire", isRegex: false, priority: 70, targetCategoryId: "cat_cagnottes" },
  { id: "r_anniv", pattern: "\\banniv\\b", isRegex: true, priority: 70, targetCategoryId: "cat_cagnottes" },
  { id: "r_felicitations", pattern: "felicitations", isRegex: false, priority: 70, targetCategoryId: "cat_cagnottes" },
  { id: "r_caisse_retour", pattern: "caisse retour", isRegex: false, priority: 70, targetCategoryId: "cat_cagnottes" },
  { id: "r_collectif", pattern: "collectif", isRegex: false, priority: 70, targetCategoryId: "cat_cagnottes" },
];

export function categoryById(categories: Category[]): Map<string, Category> {
  return new Map(categories.map((c) => [c.id, c]));
}

export function mergeDefaultCategories(categories: Category[]): Category[] {
  return mergeDefaults(DEFAULT_CATEGORIES, categories);
}

export function mergeDefaultCategoryRules(rules: CategoryRule[]): CategoryRule[] {
  return mergeDefaults(DEFAULT_CATEGORY_RULES, rules).sort((a, b) => a.priority - b.priority);
}

function mergeDefaults<T extends { id: string }>(defaults: T[], existing: T[]): T[] {
  const defaultIds = new Set(defaults.map((item) => item.id));
  const custom = existing.filter((item) => !defaultIds.has(item.id));
  return [...custom, ...defaults];
}
